[build]
  command = "npm run build"
  publish = "dist"

[functions]
  external_node_modules = ["express", "@prisma/client", "@prisma/engines"]
  node_bundler = "esbuild"
  included_files = ["prisma/schema.prisma"]

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"